### ISSUE TITLE
Response returns 200 OK on exception

### ISSUE THREAD

**Issue by saulimus** [kumuluz/kumuluzee-health#2] opened 2018-01-19 11:48 UTC
**Environment**
kumuluzee 2.5.2
kumuluzee-health 1.0.0

**Problem**
After calling health check endpoint, the response has status 200 OK even if an exception occurs.
See attachment.
The cause of the exception in this case is probably caused by: https://github.com/kumuluz/kumuluzee/issues/87

**How to reproduce**
It is quite difficult to give an example of this that would fail every time, as the problem does not happen every time. However, reproducing this manually should be trivial, by throwing an exception on the line mentioned below and seeing if the response has status 200 OK.

As shown in logs, the exception happens on this line:
```
// com.kumuluz.ee.health.HealthServlet.java:91
getWriter(request).writeValue(output, healthResponse);
```

**Attachments**
[kumuluzee_fasterxml.txt](https://github.com/kumuluz/kumuluzee-health/files/1646369/kumuluzee_fasterxml.txt)

**Comment by skrjanec** [comment] 2018-01-19 15:12
Hello,

I have reviewed your issue, but I am not able to reproduce  your problem. I have manually thrown the exact same NoSuchMethodError in line 91 as provided in your comment and log. I have also thrown an Exception in the same line. In both cases when I make a request to /health endpoint I get a response with status code of 500.

I have also reviewed my code again and all Exceptions and Errors thrown in that line should be caught and a response with status code of 500 returned.

**Comment by saulimus** [comment] 2018-01-22 10:50
Ok, I thought it might be difficult to reproduce.
Here are some screenshots of the Postman response:
![2018-01-22 12_36_21-postman](https://user-images.githubusercontent.com/2675404/35217160-df793660-ff72-11e7-9089-472f77ca52e7.png)
![2018-01-22 12_39_08-postman](https://user-images.githubusercontent.com/2675404/35217161-df99e05e-ff72-11e7-9176-429f02b53551.png)

**Comment by skrjanec** [comment] 2018-01-22 11:20
Saulimus, is there any chance that you could send me your project code? If not, could you at least provide your pom.xml and config.yaml files.

I would also need to know:

* OS and version of the environment
* JAVA version of the environment

Does this problem occour when running your project as exploaded, an Uber-jar or in both cases?

**Comment by saulimus** [comment] 2018-01-22 12:33
**Environment**
Windows 10
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) Client VM (build 25.144-b01, mixed mode, sharing)

I've only run the app using uberjar, this is probably related to the issue mentioned above, where some class files fail to (sometimes) properly load.
Maybe it would be best to wait for a fix to the aforementioned issue, I just thought this was a weird edge case and wanted to report anyway.
Here are the barebones of what config.yaml and pom.xml contain:

[example_config.yaml.txt](https://github.com/kumuluz/kumuluzee-health/files/1651902/example_config.yaml.txt)
[example_pom.xml.txt](https://github.com/kumuluz/kumuluzee-health/files/1651903/example_pom.xml.txt)

**Comment by jmezna** [comment] 2019-11-21 09:18
Closing due to the outdated version of KumuluzEE Health

**Closed as completed by jmezna** 2019-11-21 09:18 UTC
